const data = {
  products: [
    {
      name: "Free Shirts",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Populer Shirt",
    },
    {
      name: "Free Shirts",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Populer Shirt",
    },
    {
      name: "Free Shirts",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Populer Shirt",
    },
    {
      name: "Free Pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Populer Pants",
    },
    {
      name: "Free Pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Populer Pants",
    },
  ],
};
export default data;
